package modelo;
// Generated 31-jul-2017 12:27:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Advertising generated by hbm2java
 */
public class Advertising  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String image;
     private String url;
     private Date createdDate;
     private int duration;
     private Date deletionDate;
     private Set payOrders = new HashSet(0);

    public Advertising() {
    }

	
    public Advertising(User user, String image, String url, Date createdDate, int duration, Date deletionDate) {
        this.user = user;
        this.image = image;
        this.url = url;
        this.createdDate = createdDate;
        this.duration = duration;
        this.deletionDate = deletionDate;
    }
    public Advertising(User user, String image, String url, Date createdDate, int duration, Date deletionDate, Set payOrders) {
       this.user = user;
       this.image = image;
       this.url = url;
       this.createdDate = createdDate;
       this.duration = duration;
       this.deletionDate = deletionDate;
       this.payOrders = payOrders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public Date getDeletionDate() {
        return this.deletionDate;
    }
    
    public void setDeletionDate(Date deletionDate) {
        this.deletionDate = deletionDate;
    }
    public Set getPayOrders() {
        return this.payOrders;
    }
    
    public void setPayOrders(Set payOrders) {
        this.payOrders = payOrders;
    }




}


