package modelo;
// Generated 31-jul-2017 12:27:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gallery generated by hbm2java
 */
public class Gallery  implements java.io.Serializable {


     private Integer id;
     private LotDetail lotDetail;
     private String url;
     private Date deletionDate;
     private Set lotDetails = new HashSet(0);

    public Gallery() {
    }

	
    public Gallery(LotDetail lotDetail, String url, Date deletionDate) {
        this.lotDetail = lotDetail;
        this.url = url;
        this.deletionDate = deletionDate;
    }
    public Gallery(LotDetail lotDetail, String url, Date deletionDate, Set lotDetails) {
       this.lotDetail = lotDetail;
       this.url = url;
       this.deletionDate = deletionDate;
       this.lotDetails = lotDetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LotDetail getLotDetail() {
        return this.lotDetail;
    }
    
    public void setLotDetail(LotDetail lotDetail) {
        this.lotDetail = lotDetail;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getDeletionDate() {
        return this.deletionDate;
    }
    
    public void setDeletionDate(Date deletionDate) {
        this.deletionDate = deletionDate;
    }
    public Set getLotDetails() {
        return this.lotDetails;
    }
    
    public void setLotDetails(Set lotDetails) {
        this.lotDetails = lotDetails;
    }




}


