package modelo;
// Generated 02-ago-2017 17:17:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
public class Lot  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private User user;
     private String title;
     private int numSet;
     private Date expiryDate;
     private boolean individual;
     private Date createDate;
     private Date deletionDate;
     private Set lotDetails = new HashSet(0);
     private Set shares = new HashSet(0);
     private Set orders = new HashSet(0);

    public Lot() {
    }

	
    public Lot(Category category, User user, String title, int numSet, boolean individual, Date createDate) {
        this.category = category;
        this.user = user;
        this.title = title;
        this.numSet = numSet;
        this.individual = individual;
        this.createDate = createDate;
    }
    public Lot(Category category, User user, String title, int numSet, Date expiryDate, boolean individual, Date createDate, Date deletionDate, Set lotDetails, Set shares, Set orders) {
       this.category = category;
       this.user = user;
       this.title = title;
       this.numSet = numSet;
       this.expiryDate = expiryDate;
       this.individual = individual;
       this.createDate = createDate;
       this.deletionDate = deletionDate;
       this.lotDetails = lotDetails;
       this.shares = shares;
       this.orders = orders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getNumSet() {
        return this.numSet;
    }
    
    public void setNumSet(int numSet) {
        this.numSet = numSet;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public boolean isIndividual() {
        return this.individual;
    }
    
    public void setIndividual(boolean individual) {
        this.individual = individual;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getDeletionDate() {
        return this.deletionDate;
    }
    
    public void setDeletionDate(Date deletionDate) {
        this.deletionDate = deletionDate;
    }
    public Set getLotDetails() {
        return this.lotDetails;
    }
    
    public void setLotDetails(Set lotDetails) {
        this.lotDetails = lotDetails;
    }
    public Set getShares() {
        return this.shares;
    }
    
    public void setShares(Set shares) {
        this.shares = shares;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


