package modelo;
// Generated 04-ago-2017 17:52:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
public class Lot  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private User user;
     private String title;
     private String desciption;
     private int numSet;
     private float price;
     private String photo;
     private Date expiryDate;
     private Date createDate;
     private Date deletionDate;
     private Set shares = new HashSet(0);
     private Set orders = new HashSet(0);
     private Set lotDetails = new HashSet(0);

    public Lot() {
    }

	
    public Lot(Category category, User user, String title, String desciption, int numSet, float price, String photo, Date expiryDate, Date createDate) {
        this.category = category;
        this.user = user;
        this.title = title;
        this.desciption = desciption;
        this.numSet = numSet;
        this.price = price;
        this.photo=photo;
        this.expiryDate = expiryDate;
        this.createDate = createDate;
    }
    public Lot(Category category, User user, String title, String desciption, int numSet, float price, String photo, Date expiryDate, Date createDate, Date deletionDate, Set shares, Set orders, Set lotDetails) {
       this.category = category;
       this.user = user;
       this.title = title;
       this.desciption = desciption;
       this.numSet = numSet;
       this.price = price;
       this.photo = photo;
       this.expiryDate = expiryDate;
       this.createDate = createDate;
       this.deletionDate = deletionDate;
       this.shares = shares;
       this.orders = orders;
       this.lotDetails = lotDetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }
    public int getNumSet() {
        return this.numSet;
    }
    
    public void setNumSet(int numSet) {
        this.numSet = numSet;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getDeletionDate() {
        return this.deletionDate;
    }
    
    public void setDeletionDate(Date deletionDate) {
        this.deletionDate = deletionDate;
    }
    public Set getShares() {
        return this.shares;
    }
    
    public void setShares(Set shares) {
        this.shares = shares;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getLotDetails() {
        return this.lotDetails;
    }
    
    public void setLotDetails(Set lotDetails) {
        this.lotDetails = lotDetails;
    }




}


