package modelo;
// Generated 30-ago-2017 1:10:38 by Hibernate Tools 4.3.1



/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod  implements java.io.Serializable {


     private Integer id;
     private String type;

    public PaymentMethod() {
    }

    public PaymentMethod(String type) {
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


