package modelo;
// Generated 31-jul-2017 12:27:36 by Hibernate Tools 4.3.1



/**
 * Share generated by hbm2java
 */
public class Share  implements java.io.Serializable {


     private Integer id;
     private Channel channel;
     private Lot lot;
     private User user;

    public Share() {
    }

    public Share(Channel channel, Lot lot, User user) {
       this.channel = channel;
       this.lot = lot;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Channel getChannel() {
        return this.channel;
    }
    
    public void setChannel(Channel channel) {
        this.channel = channel;
    }
    public Lot getLot() {
        return this.lot;
    }
    
    public void setLot(Lot lot) {
        this.lot = lot;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


